### ISSUE TITLE
Version update action not working

### ISSUE THREAD

**Issue by atanasantonov** [zotapay/zota-for-woocommerce#25]
I made some changes to showing icons on the checkout normally. Then replaced the plugin on the staging site and realized that the version of the new branch is 1.1.3 but the release is 1.1.5. Also we're defining constant ZOTA_WC_VERSION in plugin starter file zota-for-woocommerce.php which is not included in the Prepare release step. @gonzomir @alexbhr guys does anybody has a suggestion how to proceed with that?

**Comment by alexbhr** [comment]
Guys, I suggest looking [here](https://github.com/zotapay/zota-for-woocommerce/blob/41152d5dfb33d9fba79b2dfaa4b31f29a0d82c62/.github/workflows/plugin-release.yml#L44) and making similar adjustments at release time. I briefly mentioned this in another PR at the time.

**Comment by atanasantonov** [comment]
Yes, it seems ok but probably the regex needs adjustment. Suppose that whitespaces are not as has to be. Will check that and try to make some tests before pushing the next tag.

**Comment by atanasantonov** [comment]
Now the release is ok, but master stays unchanged. @alexbhr can we make to update the files in master because it's little confusing when in main file for example stays something like 1.1.3?

**Comment by alexbhr** [comment]
Sorry @atanasantonov - was on the road for two weeks. Please, adjust the regular expressions as you see fit so that the appropriate changes take place. Alternatively, I can do it if you provide a list with files and values that need changing...

**Comment by atanasantonov** [comment]
Hey @alexbhr regex is fine as well as one more substitution added. Because that's a WordPress plugin and to avoid updates from the repository by mistake during the development probably we can change the version before tagging. What do you think about it?

**Comment by atanasantonov** [comment]
I'm closing this because it's ok. :)
